### ISSUE TITLE
cecilia crashes on mac sonoma

### ISSUE THREAD

**Issue by fyfyfyfyfufu** [belangeo/cecilia5#115]
When i run python3 Cecilia5.py in terminal, I keep getting this importerror. 
I copied cecilia from git using brew. 
will someone be kind enough to give me a hand?
thxx!!

Here is the log:
f--@F-deMacBook-Pro cecilia5 % python3 Cecilia5.py     
Traceback (most recent call last):
  File "/Users/f--/cecilia5/Cecilia5.py", line 25, in <module>
    from Resources.Variables import loadBitmaps
  File "/Users/f--/cecilia5/Resources/Variables.py", line 24, in <module>
    from pyo import pa_get_default_devices_from_host
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyo/__init__.py", line 27, in <module>
    from .lib import analysis as analysis
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyo/lib/analysis.py", line 30, in <module>
    from ._core import *
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyo/lib/_core.py", line 47, in <module>
    from .._pyo import *

**ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyo/_pyo.cpython-39-darwin.so, 0x0002): Library not loaded: /usr/local/opt/portmidi/lib/libportmidi.2.dylib
  Referenced from: <78B0673F-3268-3F31-9BA8-28BBA13A1699> /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyo/_pyo.cpython-39-darwin.so
  Reason: tried: '/usr/local/opt/portmidi/lib/libportmidi.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/portmidi/lib/libportmidi.2.dylib' (no such file), '/usr/local/opt/portmidi/lib/libportmidi.2.dylib' (no such file), '/usr/lib/libportmidi.2.dylib' (no such file, not in dyld cache)**

**Comment by fyfyfyfyfufu** [comment]
Just paid for a tech guy to solve this problem for me. 
I'd love to post the solution, hopefully this may help someone :)

He firstly uninstalled my latest version of pyo (by today it's 1.0.5)
and tried all the previous versions of pyo for my computer (mac m3 sonoma 14.3) until he found the 1.0.4 that works.
For all the other versions, terminal says there is no wheel for the pyo.


Actually I had this problem coming up when I firstly installed pyo 1.0.5, at that time I had another guy help me dealing with this problem, he just downloaded a wheel file for the pyo. It looks like the problem is solved cause you have all the needed dependencies installed and cecilia is supposed to launch properly. But just by adding a wheel for a pyo that doesn't work for your computer actually won't help.

So If coming across this error, just ignore it and try the previous versions.

here is the code:

uninstall pyo:  pip3 uninstall pyo -y
check the previous versions:  pip3 install pyo==
install 1.0.4: pip3 install pyo==1.0.4

**Comment by oivindi** [comment]
Ah, wow! So this means you really got Cecilia to run on Sonoma?! :) Anyone else tried this?
