### ISSUE TITLE
Another Ceclia starup issue Sonoma

### ISSUE THREAD

**Issue by zseramnay** [belangeo/cecilia5#116]
Hi,

Trying to run Ceclia from sources gives me this error.
It looks different from the ones discussed here before...
Ay ideas ?

I must say I very anxious about the perspective of not being able to use Ceclia anymore. I also taught it to  lot of students over the years and...

We have to find a way to maintain it !
Best

Yan Maresz
----------------------------
Last login: Wed May  8 11:16:54 on console
(base) yanmaresz@yanmaresz ~ % cd /Users/yanmaresz/kDrive/Dev/Sources/cecilia5 
(base) yanmaresz@yanmaresz cecilia5 % ls
Cecilia5.py	Resources	images		scripts		whatsnew.md
README.rst	doc-en		release_notes	setup.py
(base) yanmaresz@yanmaresz cecilia5 % python3 Cecilia5.py
Loading Cecilia Preferences...

Traceback (most recent call last):
  File "/Users/yanmaresz/anaconda3/lib/python3.11/site-packages/wx/core.py", line 2346, in Notify
    self.notify()
  File "/Users/yanmaresz/anaconda3/lib/python3.11/site-packages/wx/core.py", line 3552, in Notify
    self.result = self.callable(*self.args, **self.kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yanmaresz/kDrive/Dev/Sources/cecilia5/Resources/splash.py", line 102, in OnClose
    self.callback()
  File "/Users/yanmaresz/kDrive/Dev/Sources/cecilia5/Cecilia5.py", line 59, in onStart
    ceciliaMainFrame.onOpen(CeciliaLib.getVar("lastCeciliaFile"),
  File "/Users/yanmaresz/kDrive/Dev/Sources/cecilia5/Resources/CeciliaMainFrame.py", line 227, in onOpen
    CeciliaLib.openCeciliaFile(self, event, builtin)
  File "/Users/yanmaresz/kDrive/Dev/Sources/cecilia5/Resources/CeciliaLib.py", line 755, in openCeciliaFile
    if not getVar("audioServer").openCecFile(cecFilePath):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yanmaresz/kDrive/Dev/Sources/cecilia5/Resources/audio.py", line 1788, in openCecFile
    CeciliaLib.getVar("mainFrame").onUpdateInterface(None)
  File "/Users/yanmaresz/kDrive/Dev/Sources/cecilia5/Resources/CeciliaMainFrame.py", line 305, in onUpdateInterface
    ceciliaInterface = CeciliaInterface.CeciliaInterface(None, title='Interface - %s' % title, mainFrame=self)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yanmaresz/kDrive/Dev/Sources/cecilia5/Resources/CeciliaInterface.py", line 56, in __init__
    self.grapher = getGrapher(self)
                   ^^^^^^^^^^^^^^^^
  File "/Users/yanmaresz/kDrive/Dev/Sources/cecilia5/Resources/Grapher.py", line 1646, in getGrapher
    return CECGrapher(parent)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/yanmaresz/kDrive/Dev/Sources/cecilia5/Resources/Grapher.py", line 1330, in __init__
    self.toolbar = ToolBar(self, tools=['save', 'load', 'reset', 'show'],
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yanmaresz/kDrive/Dev/Sources/cecilia5/Resources/Grapher.py", line 1172, in __init__
    self.convertSlider = ConvertSlider(self, self.GetParent())
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yanmaresz/kDrive/Dev/Sources/cecilia5/Resources/Grapher.py", line 1577, in __init__
    PlainSlider.__init__(self, parent, 50, 2500, 200, log=True, outFunction=self.onSlider1)
  File "/Users/yanmaresz/kDrive/Dev/Sources/cecilia5/Resources/Widgets.py", line 2037, in __init__
    self.createKnobBitmap()
  File "/Users/yanmaresz/kDrive/Dev/Sources/cecilia5/Resources/Widgets.py", line 2065, in createKnobBitmap
    rec = wx.Rect(0, h2, w, self.sliderHeight)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Rect(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 4 has unexpected type 'float'
  overload 3: argument 1 has unexpected type 'int'
  overload 4: argument 1 has unexpected type 'int'
  overload 5: argument 1 has unexpected type 'int'
  overload 6: argument 1 has unexpected type 'int'

**Comment by zseramnay** [comment]
same think using pythonw

**Comment by funxiun** [comment]
I guess I found a solution: #119
