### ISSUE TITLE
cecilia5 crash on sonama macOS 

### ISSUE THREAD

**Issue by kamalbdrgrg** [belangeo/cecilia5#117]
![Uploading Screenshot 2024-05-16 at 11.47.17 AM.png…]()
/Desktop/cecilia5 master
> python3.10 -m pip install --user pyo wxPython numpy 
Collecting pyo
  Downloading pyo-1.0.5-cp310-cp310-macosx_13_0_arm64.whl.metadata (2.4 kB)
Collecting wxPython
  Downloading wxPython-4.2.1-cp310-cp310-macosx_10_10_universal2.whl.metadata (2.9 kB)
Collecting numpy
  Downloading numpy-1.26.4-cp310-cp310-macosx_11_0_arm64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 kB 1.6 MB/s eta 0:00:00
Collecting pillow (from wxPython)
  Downloading pillow-10.3.0-cp310-cp310-macosx_11_0_arm64.whl.metadata (9.2 kB)
Collecting six (from wxPython)
  Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Downloading pyo-1.0.5-cp310-cp310-macosx_13_0_arm64.whl (9.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.7/9.7 MB 2.2 MB/s eta 0:00:00
Downloading wxPython-4.2.1-cp310-cp310-macosx_10_10_universal2.whl (31.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 31.5/31.5 MB 6.0 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp310-cp310-macosx_11_0_arm64.whl (14.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.0/14.0 MB 8.5 MB/s eta 0:00:00
Downloading pillow-10.3.0-cp310-cp310-macosx_11_0_arm64.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 9.2 MB/s eta 0:00:00
Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: six, pyo, pillow, numpy, wxPython
  WARNING: The script epyo is installed in '/Users/kamalgurung/Library/Python/3.10/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  NOTE: The current PATH contains path(s) starting with `~`, which may not be expanded by all applications.
  WARNING: The script f2py is installed in '/Users/kamalgurung/Library/Python/3.10/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  NOTE: The current PATH contains path(s) starting with `~`, which may not be expanded by all applications.
  WARNING: The scripts helpviewer, img2png, img2py, img2xpm, pycrust, pyshell, pyslices, pyslicesshell, pywxrc, wxdemo, wxdocs and wxget are installed in '/Users/kamalgurung/Library/Python/3.10/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  NOTE: The current PATH contains path(s) starting with `~`, which may not be expanded by all applications.
Successfully installed numpy-1.26.4 pillow-10.3.0 pyo-1.0.5 six-1.16.0 wxPython-4.2.1

~/Desktop/cecilia5 master 17s
> ls
Cecilia5.py	README.rst	Resources	doc-en		docs		images		release_notes	scripts		setup.py	whatsnew.md

~/Desktop/cecilia5 master
> python3.10 Cecilia5.py                             
Traceback (most recent call last):
  File "/Users/kamalgurung/Desktop/cecilia5/Cecilia5.py", line 25, in <module>
    from Resources.Variables import loadBitmaps
  File "/Users/kamalgurung/Desktop/cecilia5/Resources/Variables.py", line 24, in <module>
    from pyo import pa_get_default_devices_from_host
  File "/Users/kamalgurung/Library/Python/3.10/lib/python/site-packages/pyo/__init__.py", line 27, in <module>
    from .lib import analysis as analysis
  File "/Users/kamalgurung/Library/Python/3.10/lib/python/site-packages/pyo/lib/analysis.py", line 30, in <module>
    from ._core import *
  File "/Users/kamalgurung/Library/Python/3.10/lib/python/site-packages/pyo/lib/_core.py", line 47, in <module>
    from .._pyo import *
ImportError: dlopen(/Users/kamalgurung/Library/Python/3.10/lib/python/site-packages/pyo/_pyo.cpython-310-darwin.so, 0x0002): Library not loaded: /opt/homebrew/opt/flac/lib/libFLAC.12.dylib
  Referenced from: <E6408A3F-C3F8-30CD-906D-54CA42ADE3E5> /Users/kamalgurung/Library/Python/3.10/lib/python/site-packages/pyo/libsndfile.1.dylib
  Reason: tried: '/opt/homebrew/opt/flac/lib/libFLAC.12.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/flac/lib/libFLAC.12.dylib' (no such file), '/opt/homebrew/opt/flac/lib/libFLAC.12.dylib' (no such file), '/usr/local/lib/libFLAC.12.dylib' (no such file), '/usr/lib/libFLAC.12.dylib' (no such file, not in dyld cache)

<img width="1800" alt="Screenshot 2024-05-16 at 11 47 17 AM" src="https://github.com/belangeo/cecilia5/assets/130267794/60740944-79dd-4ae7-93e2-00729765516e">

[``](url)

**Comment by kamalbdrgrg** [comment]
startup issues in macoOS sonama to use the cecili5. Please solve it fast, I need it for my project.

**Comment by oivindi** [comment]
The software has been abandoned, happened long ago, so don't wait for solutions.

Did you try this, posted by another user? https://github.com/belangeo/cecilia5/issues/115

**Comment by kamalbdrgrg** [comment]
> The software has been abandoned, happened long ago, so don't wait for solutions.
> 
> Did you try this, posted by another user? #115

/Desktop/cecilia5 master
> python3.10 Cecilia5.py
Traceback (most recent call last):
  File "/Users/kamalgurung/Desktop/cecilia5/Cecilia5.py", line 25, in <module>
    from Resources.Variables import loadBitmaps
  File "/Users/kamalgurung/Desktop/cecilia5/Resources/Variables.py", line 24, in <module>
    from pyo import pa_get_default_devices_from_host
  File "/Users/kamalgurung/Library/Python/3.10/lib/python/site-packages/pyo/__init__.py", line 27, in <module>
    from .lib import analysis as analysis
  File "/Users/kamalgurung/Library/Python/3.10/lib/python/site-packages/pyo/lib/analysis.py", line 30, in <module>
    from ._core import *
  File "/Users/kamalgurung/Library/Python/3.10/lib/python/site-packages/pyo/lib/_core.py", line 47, in <module>
    from .._pyo import *
ImportError: dlopen(/Users/kamalgurung/Library/Python/3.10/lib/python/site-packages/pyo/_pyo.cpython-310-darwin.so, 0x0002): Library not loaded: /opt/homebrew/opt/flac/lib/libFLAC.12.dylib
  Referenced from: <E6408A3F-C3F8-30CD-906D-54CA42ADE3E5> /Users/kamalgurung/Library/Python/3.10/lib/python/site-packages/pyo/libsndfile.1.dylib
  Reason: tried: '/opt/homebrew/opt/flac/lib/libFLAC.12.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/flac/lib/libFLAC.12.dylib' (no such file), '/opt/homebrew/opt/flac/lib/libFLAC.12.dylib' (no such file), '/usr/local/lib/libFLAC.12.dylib' (no such file), '/usr/lib/libFLAC.12.dylib' (no such file, not in dyld cache)

~/Desktop/cecilia5 master
> python3 Cecilia5.py    
Traceback (most recent call last):
  File "Cecilia5.py", line 23, in <module>
    import wx
ModuleNotFoundError: No module named 'wx'

Got this issues after trying only using your recomended package for pyo but using latest version of Sonama. 
Did I have to use as you said version of Sonama of MacOS?
