### ISSUE TITLE
Not compatible with wxpython 3.0

### ISSUE THREAD

**Issue by GoogleCodeExporter** [belangeo/cecilia5#62]
```
Running cecilia5 from svn trunk fails to load with wxpython 3.0. Using wxpython 
2.8 opens the application as expected.

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/wx-3.0-gtk2/wx/_misc.py", line 1367, in Notify
    self.notify()
  File "/usr/lib/python2.7/site-packages/wx-3.0-gtk2/wx/_core.py", line 16866, in Notify
    self.result = self.callable(*self.args, **self.kwargs)
  File "/dev/shm/asd-tonyctl/home/tonyctl/sync/cecilia5-read-only/Resources/splash.py", line 78, in OnClose
    self.callback()
  File "./Cecilia5.py", line 68, in onStart
    ceciliaMainFrame.onOpen(os.path.join(MODULES_PATH, category, file), True)
  File "/dev/shm/asd-tonyctl/home/tonyctl/sync/cecilia5-read-only/Resources/CeciliaMainFrame.py", line 238, in onOpen
    CeciliaLib.openCeciliaFile(self, event, builtin)
  File "/dev/shm/asd-tonyctl/home/tonyctl/sync/cecilia5-read-only/Resources/CeciliaLib.py", line 597, in openCeciliaFile
    getVar("audioServer").openCecFile(cecFilePath)
  File "/dev/shm/asd-tonyctl/home/tonyctl/sync/cecilia5-read-only/Resources/audio.py", line 1661, in openCecFile
    CeciliaLib.getVar("mainFrame").onUpdateInterface(None)
  File "/dev/shm/asd-tonyctl/home/tonyctl/sync/cecilia5-read-only/Resources/CeciliaMainFrame.py", line 328, in onUpdateInterface
    ceciliaInterface = CeciliaInterface.CeciliaInterface(None, title='Interface - %s' % title, mainFrame=self)
  File "/dev/shm/asd-tonyctl/home/tonyctl/sync/cecilia5-read-only/Resources/CeciliaInterface.py", line 52, in __init__
    self.controlPanel = Control.CECControl(self, -1)
  File "/dev/shm/asd-tonyctl/home/tonyctl/sync/cecilia5-read-only/Resources/Control.py", line 108, in __init__
    self.sizerMain.Add(Separator(self, (230,2), colour=BORDER_COLOUR), 1, wx.EXPAND)
  File "/usr/lib/python2.7/site-packages/wx-3.0-gtk2/wx/_core.py", line 14456, in Add
    return _core_.Sizer_Add(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "Assert failure" failed at 
./src/common/sizer.cpp(1401) in DoInsert(): too many items (4 > 1*3) in grid 
sizer (maybe you should omit the number of either rows or columns?)
```

Original issue reported on code.google.com by `tonyctl...@gmail.com` on 21 Mar 2014 at 6:12

**Comment by belangeo** [comment]
Done.
