### ISSUE TITLE
Error when loading an input file in Windows 10

### ISSUE THREAD

**Issue by denisfitz57** [belangeo/cecilia5#98]
I get the following (binary download 5.4.1; note there is no admin directory in c:\users):

Traceback (most recent call last):
  File "Resources\Widgets.py", line 246, in MouseDown
    self.emptyFunction()
  File "Resources\Control.py", line 792, in onLoadFile
    self.updateMenuFromPath(path)
  File "Resources\Control.py", line 820, in updateMenuFromPath
    self.folderInfo = CeciliaLib.getVar("audioServer").getSoundsFromList(pathList)
  File "Resources\audio.py", line 2042, in getSoundsFromList
    infos = self.getSoundInfo(path)
  File "Resources\audio.py", line 2009, in getSoundInfo
    info = sndinfo(path)
  File "pyo\lib\_core.py", line 189, in sndinfo
  File "pyo\lib\_core.py", line 160, in stringencode
  File "c:\users\admin\appdata\local\programs\python\python37\lib\encodings\cp1252.py", line 12, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u010d' in position 29: character maps to <undefined>

**Comment by belangeo** [comment]
Hi, the problem is a non-ascii character in a soundfile path, and the codec is unable to encode it correctly. You can workaround this by trashing the ".cecilia5" folder, located in your home directory, and use only plain ascii characters in folder and file names.

**Comment by gysy-beep** [comment]
I just tried trashing the ".cecilia5" folder and it did not work. This is the error I get now.

Traceback (most recent call last):
  File "Resources\Widgets.py", line 246, in MouseDown
    self.emptyFunction()
  File "Resources\Control.py", line 792, in onLoadFile
    self.updateMenuFromPath(path)
  File "Resources\Control.py", line 820, in updateMenuFromPath
    self.folderInfo = CeciliaLib.getVar("audioServer").getSoundsFromList(pathList)
  File "Resources\audio.py", line 2042, in getSoundsFromList
    infos = self.getSoundInfo(path)
  File "Resources\audio.py", line 2009, in getSoundInfo
    info = sndinfo(path)
  File "pyo\lib\_core.py", line 189, in sndinfo
  File "pyo\lib\_core.py", line 160, in stringencode
  File "c:\users\admin\appdata\local\programs\python\python37\lib\encodings\cp1252.py", line 12, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 25-69: character maps to <undefined>

**Comment by belangeo** [comment]
Hi,

*and* use only plain ascii characters in folder and file names. Looks like
you have non-ASCII characters in your soundfile path.

Olivier

**Comment by gysy-beep** [comment]
I figured out by reading the manual that I had to install the source code and other various programs.

Thank you for making Cecilia.
